before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
notifications:
  webhooks:
    urls:
      - https://webhooks.tfle.xyz/travis
    on_start: always